### ISSUE TITLE
Add url routes for pages on the site

### ISSUE THREAD

**Issue by bngwanforbi** [bngwanforbi/fresh_start#3]
## Overview

- Setting up url routes to start directing people to pages we'd like them to see.

## Technical Notes

- Create a two new functions called home and about to handle traffic from the home and about page of site. Function to return what we want the user to see when they're sent to this route.
- Create new module in fresh_start directory called urls.py to map the urls that we want to correspond to each view function.

**Comment by Intheloop83** [comment]
Completed
